---
initdDir: /etc/init.d
runlevelsDir: /etc/runlevels

services:
  - name: dbus
    runlevel: default
    mandatory: false
  - name: NetworkManager
    runlevel: default
    mandatory: false

disable: []
