---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    false
showDonateUrl:          false

requirements:
    requiredStorage:    10.0
    requiredRAM:        2.0
    internetCheckUrl:   http://google.com
    check:
        - storage
        - ram
        - power
        - internet
        - root
    required:
        - storage
        - ram
        - root
